---
- hosts: all
  vars:
    work_dir: /home/com/vats/web/user
    service_name: vats-api-user
  tasks:
    - name: stop service
      command: "{{ work_dir }}/appclient.sh stop"
      
    - name: deploy war
      copy: src="{{ work_dir }}/{{ service_name }}.war" dest="{{ work_dir }}/{{ service_name }}.war" backup=yes
      
    - name: rm auto unzip war directory
      file: path={{ work_dir }}/{{ service_name }} state=absent
      
    - name: start service 
      command: "{{ work_dir }}/appclient.sh start"
      
