---
- hosts: all
  gather_facts: True
  vars:
    hostname: jenkins.vats.com.cn
    ip: 192.168.15.36
    
  tasks:
    - name: init sshd service
      template: src='files/sys/sshd_config' dest='/etc/ssh/sshd_config' mode=0600 owner=root group=root
      
    - name: init yum repo to aliyun
      template: src={{ item.src }} dest={{ item.dest }} mode=0755 owner=root group=root
      with_items:
        - {"src": 'files/sys/CentOS-Base.repo', 'dest': '/etc/yum.repos.d/CentOS-Base.repo' }
        - {"src": 'files/sys/epel-6.repo', 'dest': '/etc/yum.repos.d/epel-6.repo'}
        - {"src": 'files/sys/inittab', 'dest': '/etc/inittab'}
        - {"src": 'files/sys/config', 'dest': '/etc/selinux/config'}
        - {"src": 'files/sys/network', 'dest': '/etc/sysconfig/network'}
        - {"src": 'files/sys/ifcfg-eth0', 'dest': '/etc/sysconfig/network-scripts/ifcfg-eth0'}
        
      when:  ansible_distribution_major_version == "6"
      
    - name: rm network rules
      file: path=/etc/udev/rules.d/70-persistent-net.rules state=absent

    - name: stop iptables
      service: name=iptables state=stopped enabled=no
      
    - name: systemc update
      yum: name="{{ item }}"  state=latest
      with_items:
        - "*"
        - lrzsz
      notify:
        - reboot      
  handlers:
    - name: restart sshd
      service: name=sshd state=restarted
    - name: reboot
      shell: reboot
