---
- hosts: all
  gather_facts: false
  tasks:
    - name: init sshd service
      template: src='files/sys/sshd_config' dest='/etc/sshd_config' mode=0600 owner=root group=root
      notify:
        restart sshd
        
    - name: init yum repo to aliyun
      template: src='files/sys/CentOS-Base.repo' dest='/etc/yum.repos.d/CentOS-Base.repo' mode=0600 owner=root group=root

    - name: init yum epel to aliyun
      template: src='files/sys/epel-6.repo' dest='/etc/yum.repos.d/epel-6.repo' mode=0600 owner=root group=root

    - name: zabbix agent
      template: src='files/monitor/zabbix_agent.tar.gz' dest='/usr/local/' state=file
      notify:
        start zabbix
        
  handlers:
    - name: restart sshd
      service: name=sshd state=restarted
    - name: start zabbix
      action: shell tar xzvf /usr/local/zabbix_agent.tar.gz; /usr/local/zabbix_agent/zabbix_agentd -c /usr/local/zabbix_agent/conf/zabbix_agentd.conf