---
- hosts: all
  gather_facts: True
  tasks:
    - name: zabbix agent on centos 6
      yum: name=http://repo.zabbix.com/zabbix/3.2/rhel/6/x86_64/zabbix-agent-3.2.2-1.el6.x86_64.rpm state=present
      when: ansible_distribution_major_version == "6"
      
    - name: zabbix agent on centos 7
      yum: name=http://repo.zabbix.com/zabbix/3.2/rhel/7/x86_64/zabbix-get-3.2.2-1.el7.x86_64.rpm state=present
      when: ansible_distribution_major_version == "7"
      
      
    - name: zabbix conf directory
      file: path=/usr/local/zabbix_agent/conf/zabbix_agentd state=directory mode=0644

    - name: zabbix conf
      copy: src='files/monitor/zabbix_agentd.conf'  dest='/etc/zabbix/zabbix_agentd.conf'
      notify:
        - restart zabbix_agent
        
    - name: zabbix agent start
      service: name=zabbix-agent state=started
      
  handlers:
    - name: restart zabbix_agent
      service: name=zabbix-agent state=restarted

