# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 11:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='机柜号')),
                ('power', models.CharField(blank=True, max_length=50, null=True, verbose_name='机柜电源')),
            ],
            options={
                'verbose_name_plural': '机柜',
                'verbose_name': '机柜',
            },
        ),
        migrations.CreateModel(
            name='Idc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='机房名')),
                ('address', models.CharField(blank=True, max_length=50, null=True, verbose_name='地址')),
                ('phone', models.CharField(blank=True, max_length=25, null=True, verbose_name='电话')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱')),
                ('user_interface', models.CharField(blank=True, max_length=50, null=True, verbose_name='联系人')),
                ('user_phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='联系电话')),
                ('status', models.CharField(blank=True, max_length=50, null=True, verbose_name='状态')),
            ],
            options={
                'verbose_name_plural': '机房',
                'verbose_name': '机房',
            },
        ),
        migrations.CreateModel(
            name='Manufactures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='制造商名称')),
            ],
            options={
                'verbose_name_plural': '制造商',
                'verbose_name': '制造商',
            },
        ),
        migrations.CreateModel(
            name='Power',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_power', models.CharField(blank=True, max_length=50, null=True, verbose_name='电源功率')),
            ],
            options={
                'verbose_name_plural': '电源',
                'verbose_name': '电源',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='服务名称')),
                ('pid', models.IntegerField(blank=True, null=True, verbose_name='服务器标识')),
                ('dev_interface', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='设备接口')),
                ('op_interface', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='人员接口')),
            ],
            options={
                'verbose_name_plural': '产品线',
                'verbose_name': '产品线',
            },
        ),
        migrations.CreateModel(
            name='Raid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='RAID')),
            ],
            options={
                'verbose_name_plural': '磁盘阵列',
                'verbose_name': '磁盘阵列',
            },
        ),
        migrations.CreateModel(
            name='RaidType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='RAID卡类型')),
            ],
            options={
                'verbose_name_plural': 'RAID卡类型',
                'verbose_name': 'RAID卡类型',
            },
        ),
        migrations.CreateModel(
            name='Satus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='状态')),
            ],
            options={
                'verbose_name_plural': '状态',
                'verbose_name': '状态',
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.CharField(blank=True, max_length=50, null=True, verbose_name='供应商')),
                ('manufacturers', models.CharField(blank=True, max_length=50, null=True, verbose_name='制造商')),
                ('manufacture_date', models.DateField(verbose_name='制造日期')),
                ('server_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='类型')),
                ('SN', models.CharField(blank=True, max_length=50, null=True, verbose_name='序号')),
                ('assert_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='资产编号')),
                ('idc', models.CharField(blank=True, max_length=50, null=True, verbose_name='机房')),
                ('uuid', models.CharField(blank=True, max_length=50, null=True, verbose_name='唯一标识')),
                ('cabinet', models.CharField(blank=True, max_length=50, null=True, verbose_name='机柜')),
                ('cabinet_pos', models.CharField(blank=True, max_length=50, null=True, verbose_name='机柜位置')),
                ('expire_data', models.DateField(verbose_name='过期时间')),
                ('ups', models.BooleanField(choices=[(0, '无'), (1, '有')], verbose_name='UPS')),
                ('parter', models.CharField(max_length=50, verbose_name='管理者')),
                ('os', models.CharField(max_length=50, verbose_name='系统版本')),
                ('hostname', models.CharField(max_length=50, verbose_name='主机名')),
                ('inner_ip', models.GenericIPAddressField(verbose_name='内网地址')),
                ('port', models.CharField(default='', max_length=200, verbose_name='开放端口')),
                ('max_addr', models.CharField(max_length=50, verbose_name='MAC地址')),
                ('ipinfo', models.CharField(max_length=50, verbose_name='地址信息')),
                ('server_uptime', models.DateField(verbose_name='开机时间')),
                ('server_cpu', models.CharField(max_length=50, verbose_name='CPU信息')),
                ('server_disk', models.CharField(max_length=50, verbose_name='硬盘信息')),
                ('server_mem', models.CharField(max_length=50, verbose_name='内存信息')),
                ('raid', models.CharField(max_length=50, verbose_name='RAID')),
                ('raid_card', models.CharField(max_length=50, verbose_name='RAID型号')),
                ('status', models.IntegerField(default=0, verbose_name='状态')),
                ('comment', models.TextField(blank=True, default='', null=True, verbose_name='备注')),
                ('check_update_time', models.DateTimeField(verbose_name='检查时间')),
                ('last_op_time', models.DateTimeField(verbose_name='上次操作时间')),
                ('last_op_people', models.CharField(blank=True, max_length=50, null=True, verbose_name='上次操作人')),
                ('monitor_mail_group', models.CharField(blank=True, max_length=50, null=True, verbose_name='监控组')),
                ('vm_status', models.CharField(max_length=50, verbose_name='机器状态')),
            ],
            options={
                'verbose_name_plural': '服务器',
                'verbose_name': '服务器',
            },
        ),
        migrations.CreateModel(
            name='ServerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='服务器类型')),
                ('manufacturers_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.Manufactures')),
            ],
            options={
                'verbose_name_plural': '服务器类型',
                'verbose_name': '服务器类型',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='供应商名称')),
                ('user', models.CharField(blank=True, max_length=50, null=True, verbose_name='联系人')),
                ('user_phone', models.CharField(blank=True, max_length=25, null=True, verbose_name='联系人电话')),
            ],
            options={
                'verbose_name_plural': '供应商',
                'verbose_name': '供应商',
            },
        ),
        migrations.AddField(
            model_name='cabinet',
            name='idc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.Idc'),
        ),
    ]
